CREATE TABLE ADOPTION
(
    ID            INT  NOT NULL PRIMARY KEY,
    ADOPTER_ID    INT  NOT NULL,
    ANIMAL_ID     INT  NOT NULL,
    ADOPTION_DATE DATE NOT NULL,
    FOREIGN KEY (ADOPTER_ID) REFERENCES ADOPTER (ID) ON DELETE RESTRICT ON UPDATE CASCADE,
    FOREIGN KEY (ANIMAL_ID) REFERENCES ANIMAL (ID) ON DELETE RESTRICT ON UPDATE CASCADE
)