DROP TABLE IF EXISTS ADOPTION;

CREATE TABLE ADOPTION
(
    ID            INT         NOT NULL PRIMARY KEY,
    ADOPTER_ID    INT         NOT NULL,
    ANIMAL_ID     INT         NOT NULL,
    ADOPTION_DATE VARCHAR(10) NOT NULL
);

INSERT INTO ADOPTION
VALUES (0, 0, 0, '2024-03-08'),
       (1, 0, 1, '2024-03-08');