DROP TABLE IF EXISTS ADOPTION;

CREATE TABLE ADOPTION
(
    ID            INT  NOT NULL PRIMARY KEY,
    ADOPTER_ID    INT  NOT NULL,
    ANIMAL_ID     INT  NOT NULL,
    ADOPTION_DATE DATE NOT NULL
)