DROP TABLE IF EXISTS CONTROL;

CREATE TABLE CONTROL
(
    ID          INT NOT NULL PRIMARY KEY,
    ADOPTION_ID INT NOT NULL,
    DATE        VARCHAR(10)
);

INSERT INTO CONTROL
VALUES (0, 0, '2024-03-08'),
       (1, 1, '2024-03-08');