CREATE TABLE VIDEO (
    ID           INT AUTO_INCREMENT PRIMARY KEY,
    URL          VARCHAR(512)  NOT NULL,
    TITLE        VARCHAR(128)  NOT NULL,
    DESCRIPTION  VARCHAR(1024) NOT NULL,
    POSTING_DATE DATE          NOT NULL
);